### ISSUE TITLE
Website crashing on firefox

### ISSUE THREAD

**Issue by mattgenious** [reactstrap/reactstrap.github.io#9]
The site https://reactstrap.github.io/ crashes on Mozilla Firefox with console reporting error:

```
ReferenceError: "Prism is not defined"
    value PrismCode.js:124
    value PrismCode.js:112
    React 3
    unstable_runWithPriority scheduler.production.min.js:18
    React 12
    <anonymous> app.js:22
    Webpack 5
react-dom.production.min.js:198:186
    React 7
    unstable_runWithPriority scheduler.production.min.js:18
    React 12
    <anonym> app.js:22
    Webpack 5
```

I have tested with Google Chrome, Microsoft Edge and Microsoft Internet Explorer.
These work fine, so as far as I can tell Firefox is the only one that presents a problem.

**Comment by kkkrist** [comment]
I'm seeing the same issue with Brave (v0.64.77 Chromium: 74.0.3729.169 macOS):

```
react-dom.production.min.js:248 Uncaught ReferenceError: Prism is not defined
    at t.value (PrismCode.js:124)
    at t.value (PrismCode.js:112)
    at Hl (react-dom.production.min.js:216)
    at ql (react-dom.production.min.js:220)
    at react-dom.production.min.js:250
    at Object.t.unstable_runWithPriority (scheduler.production.min.js:18)
    at Di (react-dom.production.min.js:250)
    at Si (react-dom.production.min.js:249)
    at Ii (react-dom.production.min.js:248)
    at Ci (react-dom.production.min.js:245)
docsearch.min.js:2 Uncaught Error: Error: No input element in the page matches #algolia-doc-search
    at Function.checkArguments (docsearch.min.js:2)
    at new DocSearch (docsearch.min.js:2)
    at Factory (docsearch.min.js:2)
    at (index):103
```

**Comment by kkkrist** [comment]
Here's all the drama ;-) https://github.com/reactstrap/reactstrap/issues/1519

**Comment by kevindice** [comment]
Same on Chrome w/ ublock origin.

**Comment by kkkrist** [comment]
uBlock Origin is whitelisting it now (try refreshing your filter lists). I guess this can be closed, it's not an issue with the reactstrap website. 

Here's to hoping some clever 3rd party tracker won't rename their script to react-dom.production.min.js or jquery.min.js in the future…

**Comment by mattgenious** [comment]
Solved it for me

**Comment by TheSharpieOne** [comment]
Also, a commit has been made to easy list to correct the issue, it should eventually make its way to all of the ad blockers which use the list.

https://github.com/easylist/easylist/commit/6dc4c8692cfdb38957de41e1c517bd13a3ad9dc0
